language: ruby
rvm:
  - 2.1

install:
  - sudo wget -NO /usr/local/bin/src https://github.com/sourcegraph/srclib/releases/download/v0.0.9/src
  - sudo chmod +x /usr/local/bin/src
  - src toolchain add sourcegraph.com/sourcegraph/srclib-ruby
  - unset BUNDLE_GEMFILE
  - bundle install
  - cd yard && bundle install && cd ..

# TODO(sqs): also test yard?
script:
  - unset BUNDLE_GEMFILE
  - src -v test -m program
